### ISSUE TITLE
Lib missing?

### ISSUE THREAD

**Issue by Macumbafeh** [BannZay/PlatesClasses#1]
Hello, i tried this addon, and i have many libs missing error.

When i checked the libs folder, some libs like LibEvents-1.0 or LibLogger-1.0 are empty.

also when i dl'd the libs, LibPrototype-1.0 inside LibEvents-1.0 is empty...

Thanks

**Comment by Macumbafeh** [comment]
Ok, i dl'd the release and it's good...

My first download was on code > download zip

**Comment by BannZay** [comment]
> Ok, i dl'd the release and it's good...

Addon has dependencies on another repositories but github does not include those when you hit "download code" button.
You should either download release (which you figured out) or download latest code using git client (https://stackoverflow.com/questions/8090761/pull-using-git-including-submodule)
